name: gh-action-terragrunt-plan
description: Create a Terraform plan
author: Alina Freydina

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  tg_version:
    description: Required Terragrunt version
    required: false
    default: "0.52.4"
  tf_version:
    description: Required Terraform version
    required: false
    default: "1.5.7"
  parallelism:
    description: Limit the number of concurrent operations
    required: false
    default: "0"
  label:
    description: A friendly name for this plan
    required: false
    default: ""
  add_github_comment:
    description: Add the plan to a GitHub PR
    required: false
    default: "true"
  destroy:
    description: Create a plan to destroy all resources
    required: false
    default: "false"

runs:
  using: docker
  image: docker://ghcr.io/wayofdev/gh-actions-terragrunt@sha256:acf2eb435b4101a7247684a756bb2ae4f22e44a093361be0fb60e3a597137868
  entrypoint: /entrypoints/tg_plan_all.sh

branding:
  icon: globe
  color: purple
